### PR TITLE
Add option ccpIframeRefreshInterval to initCCPParams

### PR DESCRIPTION
**Pull request by c-st**
*Description of changes:*
- added missing typings for the fields `ccpSynTimeout`, `ccpAckTimeout`, `ccpLoadTimeout`
- added new option`ccpIframeRefreshInterval` to customize refresh interval of iFrame

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by jagadeeshaby — CHANGES_REQUESTED** [review]
ccpIframeRefreshInterval - option does not seem to be configurable via initCCP, could you update the PR by removing the references to the same

**Comment by CGarces** [comment]
Hi @c-st 
Please take a look over #650

I think that https://github.com/amazon-connect/amazon-connect-streams/pull/650/commits/f60e72e97e4404870ce209ca5eaf764ab333bc47 supersede your PR.

Fell free to add additional feedback and rebase your PR.

**Comment by CGarces** [comment]
Looks good to me
ping @seiyako and @jagadeeshaby
This PR solve one of my issues with custom CCP

**Comment by c-st** [comment]
Hi @jagadeeshaby Thanks for looking into it. I'm not sure if I understand your comment correctly:

This parameter is now evaluated in `connect.core._refreshIframeOnTimeout()` (https://github.com/amazon-connect/amazon-connect-streams/pull/606/files#diff-8ab41fe13597e1554b5d6b4c227b5f123ff2d6726a7f3688a8b8d1224fe1d4f3R1128-R1130) which is called from `connect.core.initCCP()` (https://github.com/amazon-connect/amazon-connect-streams/pull/606/files#diff-8ab41fe13597e1554b5d6b4c227b5f123ff2d6726a7f3688a8b8d1224fe1d4f3R1078).

**Comment by c-st** [comment]
@jagadeeshaby can you please have another look? 🙏

**Pull request closed without merging**
