### PR TITLE
fix for strict mode

### PR DESCRIPTION
**Pull request by stackasaur**
#565 

I had fixed this already in #514 , but it was overwritten by #554 

Properties defined via `Object.defineProperty()` are immutable by default, so [line 21116](https://github.com/amazon-connect/amazon-connect-streams/blob/master/src/aws-client.js#L21116) doesn't actually change the value of `AWS.apiLoader.services['sts']['2011-06-15']` set on [line 2881](https://github.com/amazon-connect/amazon-connect-streams/blob/master/src/aws-client.js#L2881). This line is pointless, so I commented it out to meet strict mode guidelines.

I also confirmed that L2881 executes before L21116.

> *edit 2022-07-18*
> Fixed error in `amazon-connect-websocket-manager.js`
> strict mode doesn't allow for implicit setting of window variables, changed `function(e)` to `function(e=window)` to resolve issue.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kaushalgautam** [comment]
Is there an ETA on merging this PR? Not supporting strict mode is really hurting projects on Salesforce!

PS: Thanks @stackasaur for helping out here! :)

**Comment by kaushalgautam** [comment]
@stackasaur - did you check if it can be embedded in Aura Components/LWCs?

**Comment by stackasaur** [comment]
@kaushalgautam, this version should work in an LWC/Aura without rolling back to API 39

While waiting for the merge, You can use my [forked repository](https://github.com/stackasaur/amazon-connect-streams), run the build script, and use that file. 

**I did **NOT** add the updated output file to my commit because there were differences (like 200 deletions) in my build file that didn't match the release that I couldn't account for.

**Comment by stackasaur** [comment]
@erikohlin12 

I just made an update I think will resolve your issue now.

> Fixed error in `amazon-connect-websocket-manager.js`, 
> strict mode doesn't allow for implicit setting of window variables, changed `function(e)` to `function(e=window)`

In case this doesn't work for you, what framework are you using this library in?

**Comment by erikohlin12** [comment]
@stackasaur that fixed my issue, much appreciated!

**Comment by martin-greenberg** [comment]
Closing as we have fixed this issue in Streams 2.3.0.

**Pull request closed without merging**
